server:
  port: 8080
  servlet:
    session:
      cookie:
        name: CLIENT-SESSION

spring:
  security:
    oauth2:
      client:
        registration:
          blog-client:
            provider: client-provider
            client-id: blog-client
            client-secret: blog-client
            authorization-grant-type: authorization_code
            client-authentication-method: none
            redirect-uri: "{baseUrl}/login/oauth2/code/blog-client"
            scope: profile
            client-name: blog-client
        provider:
          client-provider:
            authorization-uri: http://127.0.0.1:8070/oauth2/authorize
            token-uri: http://127.0.0.1:8070/oauth2/token