server:
  port: 8090

logging:
  level:
    org.springframework.web: trace

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8070/oauth2/jwks
  datasource:
    url: jdbc:mysql://localhost:3306/blog_resource?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gaotianchi
    password: 20040401
  jpa:
    hibernate:
      ddl-auto: update

image:
  supported-extensions:
    - jpg
    - jpeg
    - png
    - gif
  storage:
    root-path: D:\Documents\blog\resource\uploads\images
  compression:
    enable: true
  url-pattern: "/picture/**"
