server:
  port: 8090

logging:
  level:
    org.springframework.security.web: trace
    org.springframework.security.oauth2: trace
    web: trace

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8070/oauth2/jwks
  datasource:
    url: jdbc:mysql://localhost:3306/blog_resource?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gaotianchi
    password: 20040401
  jpa:
    hibernate:
      ddl-auto: update

storage:
  illustration:
    location: "D:/documents/blog/resource/uploads/illustration"
    max-width: 300
    quality: 0.5F
    original-dir-name: "original"
    thumbnail-dir-name: "thumbnail"
    allowed-extensions:
      - ".png"
      - ".jpeg"
      - ".gif"
  series-cover:
    location: "D:/documents/blog/resource/uploads/cover"
    max-width: 600
    quality: 0.5F
    original-dir-name: "original"
    thumbnail-dir-name: "thumbnail"
    allowed-extensions:
      - ".png"
      - ".jpeg"
  avatar:
    location: "D:/documents/blog/resource/uploads/avatar"
    allowed-extensions:
      - ".png"
      - ".jpeg"

pagination:
  number-of-info-per-page:
    user-series: 10