spring:
    application:
        name: oauth2service
    datasource:
        url: jdbc:mysql://localhost:3306/blog_auth?createDatabaseIfNotExist=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: gaotianchi
        password: 20040401
    jpa:
        hibernate:
            ddl-auto: update
    security:
        oauth2:
            authorizationserver:
                client:
                    public-client:
                        registration:
                            client-id: "blog-client"
                            client-authentication-methods:
                                - "none"
                            authorization-grant-types:
                                - "authorization_code"
                            redirect-uris:
                                - "http://localhost:3000/callback"
                            scopes:
                                - "openid"
                                - "profile"
                        require-authorization-consent: false
                        require-proof-key: true

logging:
    level:
        org:
            springframework:
                security: debug

server:
    port: 9000