server:
  port: 8080
  servlet:
    session:
      cookie:
        name: CLIENT-SESSION

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          blog-client:
            provider: client-provider
            client-id: blog-client
            authorization-grant-type: authorization_code
            client-authentication-method: none
            redirect-uri: http://localhost:8080/login/oauth2/code/blog-client
            scope: profile
            client-name: blog-client
        provider:
          client-provider:
            authorization-uri: http://localhost:8070/oauth2/authorize
            token-uri: http://localhost:8070/oauth2/token